### ISSUE TITLE
Middle section: Client Testimonials

### ISSUE THREAD

**Issue by shagariboy** [RW2023/sunnyside-agency-landing-page#3]
This is for the client testimonials section(Mobile & Desktop view). Please take a look at the mobile design in the readme for reference.
![desktop-design_middle_section](https://user-images.githubusercontent.com/45914831/230879873-40f151b9-f581-4a8c-b4a1-d63840106cce.jpg)

**Comment by jeremyoduromanu** [comment]
I will complete it
